services:
  app:
    build:
      context: .
      target: runtime
    image: ${CANONICAL_DISCOVERY_APP_IMAGE:-ghcr.io/clemson-netbox/canonical-discovery}:${CANONICAL_DISCOVERY_IMAGE_TAG:-dev}
    working_dir: /workspace
    command: ["python", "--version"]

  devcontainer:
    build:
      context: .
      target: dev
    image: ${CANONICAL_DISCOVERY_DEV_IMAGE:-canonical-discovery}:${CANONICAL_DISCOVERY_DEV_TAG:-dev}
    working_dir: /workspace
    command: ["sleep", "infinity"]
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
      - poetry-venvs:/opt/poetry-venvs

volumes:
  poetry-venvs:
